---
kind: pipeline
name: default

steps:
  - name: build & push
    image: mazzolino/drone-docker-buildx:20
    settings:
      auto_tag: true
      repo: mazzolino/shepherd
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    exclude:
      - pull_request
---
kind: signature
hmac: 38ab422a8b7ec0e95f6a92c1a224bb102b8a2ed4f37501ade35ff7a4cb29729b
